### ISSUE TITLE
After Post save

### ISSUE THREAD

**Issue by Flooooooooooorian** [Pourya-Nejadensan/blog-post-app-capstone#18]
https://github.com/Pourya-Nejadensan/blog-post-app-capstone/blob/91d19560faea380e3aecbdf8820e373b0eda34db/frontend/src/pages/post/create/PostCreate.tsx#L27

Ich würde nach dem erfolgreichen erstellen des Posts, diesen in den useState mit allen alten Posts hinzufügen, damit du nicht jedes mal alle Posts neu laden musst.
Dafür würde ich den useState aus der PostList in die PostRoutes Komponente verschieben.

**Comment by Pourya-Nejadensan** [comment]
@Flooooooooooorian kannst du bitte mein Pull Request anschauen? Falls ich was ändern sollte, schreib bitte mir Kommentar.
Danke dir!
